// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutoring_Website.Model;

namespace Tutoring_Website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tutoring_Website.Model.Tutor", b =>
                {
                    b.Property<int>("tutor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("tutor_date_joined")
                        .HasColumnType("datetime2");

                    b.Property<string>("tutor_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tutor_rate")
                        .HasColumnType("int");

                    b.Property<int>("tutor_rating")
                        .HasColumnType("int");

                    b.Property<string>("tutor_subjects")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tutor_id");

                    b.ToTable("Tutors");
                });
#pragma warning restore 612, 618
        }
    }
}
